language: cpp

compiler:
  - gcc
  - clang 

before_script:
  - sudo apt-get -qq update
 
addons:
  apt:    
    packages:
     - numactl 
     - libtbb-dev
     - gcc-9
        

script: 
  - mkdir build
  - cd build 
  - cmake ../
  - make  
