language: cpp

compiler:
  - gcc
  - clang 

before_script:
  - sudo apt-get -qq update
 
addons:
  apt:    
    sources: 
     - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
     - numactl 
     - libtbb-dev
     - g++-9
        

script: 
  - mkdir build
  - cd build 
  - cmake ../
  - make  
