language: cpp

addons: 
  apt: 
    packages: 
      - numactl
      - libtbb-dev
      - g++-8
      - libnuma-dev
    sources: 
      - sourceline: "ppa:ubuntu-toolchain-r/test"
before_script: 
  - "sudo apt-get -qq update"
matrix: 
  include: 
    env: 
      - "MATRIX_EVAL=\"CC=gcc-8 && CXX=g++-8\""

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - "mkdir build"
  - "cd build"
  - "cmake ../"
  - make
